namespace MiaDock.Core.Logging;

public static class TechnicalEventIds
{
    public const string ApplicationStarting = "app.starting";
    public const string ApplicationReady = "app.ready";
    public const string ApplicationStopping = "app.stopping";
    public const string ApplicationShutdownFailed = "app.shutdown-failed";
    public const string ApplicationUnhandled = "app.unhandled";
    public const string ApplicationCrashDetected = "app.crash-detected";
    public const string ApplicationRestartRequested = "app.restart-requested";
    public const string ApplicationCrashReportSaved = "app.crash-report-saved";
    public const string AppDomainUnhandled = "runtime.unhandled";
    public const string UnobservedTask = "runtime.unobserved-task";
    public const string SettingsLoadFailed = "settings.load-failed";
    public const string SettingsSaveFailed = "settings.save-failed";
    public const string MediaSelectionFailed = "media.selection-failed";
    public const string MediaServiceStateChanged = "media.service-state-changed";
    public const string MediaTopologyRebuilt = "media.topology-rebuilt";
    public const string MediaSessionChanged = "media.session-changed";
    public const string MediaSnapshotStarted = "media.snapshot-started";
    public const string MediaSnapshotFailed = "media.snapshot-failed";
    public const string MediaTransportFailed = "media.transport-failed";
    public const string ModuleNavigationFailed = "dock.module-navigation-failed";
    public const string MediaAudioMeterFailed = "media.audio-meter-failed";
    public const string MediaAudioMeterBinding = "media.audio-meter-binding";
    public const string AudioTopologyRebind = "audio.topology-rebind";
    public const string TimerAlarmStarting = "time.alarm-starting";
    public const string TimerAlarmPlaybackFailed = "time.alarm-playback-failed";
    public const string AudibleNotificationPlaybackFailed = "notification-sound.playback-failed";
    public const string SystemActivityReady = "system-activity.ready";
    public const string CameraWatcherUnavailable = "system-activity.camera-watcher-unavailable";
    public const string PrivacyUsageMonitorFailed = "privacy.usage-monitor-failed";
    public const string PrivacyUsageReady = "privacy.usage-ready";
    public const string PowerStatusReady = "device-status.power-ready";
    public const string NetworkStatusReady = "device-status.network-ready";
    public const string NetworkCountersUnavailable = "device-status.network-counters-unavailable";
    public const string BluetoothWatcherReady = "device-status.bluetooth-ready";
    public const string DeviceStatusUnavailable = "device-status.unavailable";
    public const string TrayCommandFailed = "tray.command-failed";
    public const string LogsCleared = "logs.cleared";
    public const string LogExportFailed = "logs.export-failed";
    public const string StoreUpdateCheckCompleted = "store-update.check-completed";
    public const string StoreUpdateCheckFailed = "store-update.check-failed";
    public const string StartupTaskChecked = "startup-task.checked";
    public const string StartupTaskRepairFailed = "startup-task.repair-failed";
    public const string HotKeyRegistrationFailed = "hotkey.registration-failed";
    public const string HotKeyCommandFailed = "hotkey.command-failed";
    public const string HotKeyDispatchFailed = "hotkey.dispatch-failed";
    public const string ExternalUriLaunchFailed = "external-uri.launch-failed";
    public const string FullscreenStateChanged = "fullscreen.state-changed";
    public const string FullscreenDetectionFailed = "fullscreen.detection-failed";
    public const string FullscreenHookUnavailable = "fullscreen.hook-unavailable";
    public const string TimeStatePersistFailed = "time.state-persist-failed";
    public const string ModuleSettingsApplyFailed = "module.settings-apply-failed";
}
